### ISSUE TITLE
How do i install?

### ISSUE THREAD

**Issue by martin-wahlberg** [kodsnutten/homebridge-verisure#1]
Hi! Where is the index.js file stored? 🤔

**Comment by kodsnutten** [comment]
Hi Wahlly! I guess your question is "Where should i put the index.js file?"!

The answer is, as so often, that it depends... I guess you have run `npm install -g homebridge-verisure` which installs the released version.

That installs a lot of node modules in a global location. In a linux system that location could be "/usr/local/lib/node_modules". I'd suggest that you search your file system for the "homebridge-verisure"-folder, and when you find it you can replace the existing index.js in that folder. After you have replaced the index.js-file you also need to restart **homebridge**.

**Comment by kodsnutten** [comment]
Wow, NPM is cool :-D You can actually issue the following command to update your installation:
`npm install -g git+https://github.com/kodsnutten/homebridge-verisure.git`

**Comment by kodsnutten** [comment]
Don't forget to add the **doorcode** configuration entry, as specified in the updated [README.md](https://github.com/kodsnutten/homebridge-verisure/blob/master/README.md)

**Comment by martin-wahlberg** [comment]
Cool! Thanks for the new functionality ☺️

**Comment by kodsnutten** [comment]
Closing...
